version: "3.3"
volumes:
  postgres_volume:

services:
  # Application
  csr:
    image: csr:latest
    container_name: csrapp
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

#  PostgreSQL
  postgres:
      image: postgres:latest
      volumes:
        - postgres_volume:/var/lib/postgresql/data
      container_name: postgres
      restart: always
      environment:
        - POSTGRES_DB=csr
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
      ports:
        - "5433:5432"